#pragma once

// concat 3 variables together to form a name. e.g. PP_CREATE_CLASS_NAME(foo, bar, baz) -> foo_bar_baz
#define PP_CREATE_CLASS_NAME(x0, x1, x2) x0##_##x1##_##x2

#define PP_STRINGIZE(x) #x
#define PP_EXPAND(x) x

// Get N-th argument, up to 128 variables
#define PP_GET_NTH_ARG(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, _63, _64, _65, _66, _67, _68, _69, _70, _71, _72, _73, _74, _75, _76, _77, _78, _79, _80, _81, _82, _83, _84, _85, _86, _87, _88, _89, _90, _91, _92, _93, _94, _95, _96, _97, _98, _99, _100, _101, _102, _103, _104, _105, _106, _107, _108, _109, _110, _111, _112, _113, _114, _115, _116, _117, _118, _119, _120, _121, _122, _123, _124, _125, _126, _127, _128, N, ...) N

// helper functions that expands varadic arguments and apply each argument to _fn with _class. e.g. _fn(_class, x)
#define PP_FUNC_CALL_0(_fn, ...)
#define PP_FUNC_CALL_1(_fn, _class, x) _fn(_class, x)
#define PP_FUNC_CALL_2(_fn, _class, x, ...) _fn(_class, x) PP_FUNC_CALL_1(_fn, _class, __VA_ARGS__)
#define PP_FUNC_CALL_3(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_2(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_4(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_3(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_5(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_4(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_6(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_5(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_7(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_6(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_8(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_7(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_9(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_8(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_10(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_9(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_11(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_10(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_12(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_11(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_13(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_12(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_14(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_13(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_15(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_14(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_16(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_15(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_17(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_16(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_18(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_17(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_19(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_18(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_20(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_19(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_21(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_20(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_22(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_21(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_23(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_22(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_24(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_23(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_25(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_24(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_26(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_25(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_27(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_26(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_28(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_27(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_29(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_28(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_30(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_29(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_31(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_30(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_32(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_31(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_33(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_32(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_34(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_33(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_35(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_34(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_36(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_35(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_37(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_36(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_38(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_37(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_39(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_38(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_40(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_39(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_41(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_40(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_42(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_41(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_43(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_42(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_44(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_43(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_45(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_44(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_46(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_45(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_47(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_46(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_48(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_47(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_49(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_48(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_50(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_49(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_51(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_50(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_52(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_51(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_53(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_52(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_54(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_53(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_55(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_54(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_56(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_55(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_57(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_56(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_58(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_57(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_59(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_58(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_60(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_59(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_61(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_60(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_62(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_61(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_63(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_62(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_64(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_63(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_65(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_64(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_66(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_65(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_67(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_66(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_68(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_67(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_69(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_68(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_70(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_69(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_71(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_70(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_72(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_71(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_73(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_72(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_74(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_73(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_75(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_74(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_76(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_75(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_77(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_76(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_78(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_77(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_79(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_78(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_80(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_79(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_81(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_80(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_82(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_81(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_83(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_82(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_84(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_83(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_85(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_84(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_86(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_85(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_87(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_86(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_88(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_87(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_89(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_88(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_90(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_89(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_91(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_90(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_92(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_91(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_93(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_92(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_94(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_93(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_95(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_94(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_96(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_95(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_97(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_96(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_98(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_97(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_99(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_98(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_100(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_99(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_101(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_100(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_102(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_101(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_103(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_102(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_104(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_103(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_105(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_104(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_106(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_105(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_107(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_106(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_108(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_107(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_109(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_108(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_110(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_109(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_111(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_110(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_112(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_111(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_113(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_112(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_114(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_113(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_115(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_114(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_116(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_115(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_117(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_116(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_118(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_117(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_119(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_118(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_120(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_119(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_121(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_120(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_122(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_121(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_123(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_122(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_124(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_123(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_125(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_124(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_126(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_125(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_127(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_126(_fn, _class, __VA_ARGS__))
#define PP_FUNC_CALL_128(_fn, _class, x, ...) _fn(_class, x) PP_EXPAND(PP_FUNC_CALL_127(_fn, _class, __VA_ARGS__))

// apply function x to each varadic argument with _class, varadic supports up to 128 arguments
#define PP_FOR_EACH(x, _class, ...) PP_EXPAND(PP_GET_NTH_ARG(__VA_ARGS__, PP_FUNC_CALL_128, PP_FUNC_CALL_127, PP_FUNC_CALL_126, PP_FUNC_CALL_125, PP_FUNC_CALL_124, PP_FUNC_CALL_123, PP_FUNC_CALL_122, PP_FUNC_CALL_121, PP_FUNC_CALL_120, PP_FUNC_CALL_119, PP_FUNC_CALL_118, PP_FUNC_CALL_117, PP_FUNC_CALL_116, PP_FUNC_CALL_115, PP_FUNC_CALL_114, PP_FUNC_CALL_113, PP_FUNC_CALL_112, PP_FUNC_CALL_111, PP_FUNC_CALL_110, PP_FUNC_CALL_109, PP_FUNC_CALL_108, PP_FUNC_CALL_107, PP_FUNC_CALL_106, PP_FUNC_CALL_105, PP_FUNC_CALL_104, PP_FUNC_CALL_103, PP_FUNC_CALL_102, PP_FUNC_CALL_101, PP_FUNC_CALL_100, PP_FUNC_CALL_99, PP_FUNC_CALL_98, PP_FUNC_CALL_97, PP_FUNC_CALL_96, PP_FUNC_CALL_95, PP_FUNC_CALL_94, PP_FUNC_CALL_93, PP_FUNC_CALL_92, PP_FUNC_CALL_91, PP_FUNC_CALL_90, PP_FUNC_CALL_89, PP_FUNC_CALL_88, PP_FUNC_CALL_87, PP_FUNC_CALL_86, PP_FUNC_CALL_85, PP_FUNC_CALL_84, PP_FUNC_CALL_83, PP_FUNC_CALL_82, PP_FUNC_CALL_81, PP_FUNC_CALL_80, PP_FUNC_CALL_79, PP_FUNC_CALL_78, PP_FUNC_CALL_77, PP_FUNC_CALL_76, PP_FUNC_CALL_75, PP_FUNC_CALL_74, PP_FUNC_CALL_73, PP_FUNC_CALL_72, PP_FUNC_CALL_71, PP_FUNC_CALL_70, PP_FUNC_CALL_69, PP_FUNC_CALL_68, PP_FUNC_CALL_67, PP_FUNC_CALL_66, PP_FUNC_CALL_65, PP_FUNC_CALL_64, PP_FUNC_CALL_63, PP_FUNC_CALL_62, PP_FUNC_CALL_61, PP_FUNC_CALL_60, PP_FUNC_CALL_59, PP_FUNC_CALL_58, PP_FUNC_CALL_57, PP_FUNC_CALL_56, PP_FUNC_CALL_55, PP_FUNC_CALL_54, PP_FUNC_CALL_53, PP_FUNC_CALL_52, PP_FUNC_CALL_51, PP_FUNC_CALL_50, PP_FUNC_CALL_49, PP_FUNC_CALL_48, PP_FUNC_CALL_47, PP_FUNC_CALL_46, PP_FUNC_CALL_45, PP_FUNC_CALL_44, PP_FUNC_CALL_43, PP_FUNC_CALL_42, PP_FUNC_CALL_41, PP_FUNC_CALL_40, PP_FUNC_CALL_39, PP_FUNC_CALL_38, PP_FUNC_CALL_37, PP_FUNC_CALL_36, PP_FUNC_CALL_35, PP_FUNC_CALL_34, PP_FUNC_CALL_33, PP_FUNC_CALL_32, PP_FUNC_CALL_31, PP_FUNC_CALL_30, PP_FUNC_CALL_29, PP_FUNC_CALL_28, PP_FUNC_CALL_27, PP_FUNC_CALL_26, PP_FUNC_CALL_25, PP_FUNC_CALL_24, PP_FUNC_CALL_23, PP_FUNC_CALL_22, PP_FUNC_CALL_21, PP_FUNC_CALL_20, PP_FUNC_CALL_19, PP_FUNC_CALL_18, PP_FUNC_CALL_17, PP_FUNC_CALL_16, PP_FUNC_CALL_15, PP_FUNC_CALL_14, PP_FUNC_CALL_13, PP_FUNC_CALL_12, PP_FUNC_CALL_11, PP_FUNC_CALL_10, PP_FUNC_CALL_9, PP_FUNC_CALL_8, PP_FUNC_CALL_7, PP_FUNC_CALL_6, PP_FUNC_CALL_5, PP_FUNC_CALL_4, PP_FUNC_CALL_3, PP_FUNC_CALL_2, PP_FUNC_CALL_1, PP_FUNC_CALL_0)(x, _class, __VA_ARGS__))

// expand tuple into arguments, e.g. (foo, bar, baz) -> foo, bar, baz
#define PP_EVAL_TUPLE_IMPL(...) __VA_ARGS__
#define PP_EVAL_TUPLE(tuple) PP_EVAL_TUPLE_IMPL tuple
